@baseUrl = http://localhost:5196/api
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI4ZDdmMmY0NC04YzkxLTRmN2YtYTVmMi0xZDljM2I4YTRlMTEiLCJlbWFpbCI6Im1hcmtAZ21haWwuY29tIiwicm9sZSI6Ik1hbmFnZXIiLCJuYmYiOjE3ODAxNTY4MjMsImV4cCI6MTc4MDE2MDQyMywiaWF0IjoxNzgwMTU2ODIzLCJpc3MiOiJsb2NhbGhvc3QiLCJhdWQiOiJsb2NhbGhvc3QifQ.8ok-msx5-AIkLLImL1Hx0i_U3eUdPSTKarMwyKThaxk
@refreshToken = 3Aa5i4f+8F  2qYVQegmbzcRhYPzitWYREsMaxnzGtBGA=

@managerMarkId = 8d7f2f44-8c91-4f7f-a5f2-1d9c3b8a4e11
@managerJohnId = 1b2e9d63-6f84-4db6-b4a5-7e3c1a92f220

@laborAliceId = c4a8f9d1-3e52-47d0-9d61-2f7b6c5a8d33
@laborBobId   = 5f1c7b82-9a65-4ed4-8c27-4a9d1e6b7f44
@laborKevinId = 9e6d3a55-2b48-41f1-a3d8-8b2c7f9d5e55

@customerAhmedId = 5b1d3f5c-6f1b-7b4d-c2ce-5d6f3a1e5005
@customerSaraId  = 6c2e4a6d-7a2c-8c5e-d3df-6e7a4b2f6006

@workOrderId = 0acd43ec-4823-443a-9ddf-7c232d4e7c6c

### Login As Manager
POST {{baseUrl}}/identity/token/generate
Content-Type: application/json

{
    "email": "mark@gmail.com",
    "password": "Manager@1234!"
}

### Login As Labor
POST {{baseUrl}}/identity/token/generate
Content-Type: application/json

{
    "email": "alice@gmail.com",
    "password": "Labor@1234!"
}

### Refresh Token
POST {{baseUrl}}/identity/token/refresh-token
Content-Type: application/json

{
    "ExpiredAccessToken": "{{accessToken}}",
    "refreshToken": "{{refreshToken}}"
}

# SwaggerUI: https://localhost:7007/swagger

### Open API Document
GET https://localhost:7007/openapi/v1.json

### Get All Customers
GET {{baseUrl}}/customers
api-version: 1.0
Authorization: Bearer {{accessToken}}

### Get customer by id
GET {{baseUrl}}/customers/{{customerAhmedId}}
api-version: 1.0
Authorization: Bearer {{accessToken}}

### Get all repair task
GET {{baseUrl}}/repair-tasks
api-version: 1.0
Authorization: Bearer {{accessToken}}

### Get a Repair task
GET {{baseUrl}}/repair-tasks/1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d
api-version: 1.0
Authorization: Bearer {{accessToken}}

### Get all workorders
GET {{baseUrl}}/work-orders?pageNumber=1&pageSize=1
api-version: 1.0
Authorization: Bearer {{accessToken}}

### Search workorders
GET {{baseUrl}}/work-orders?pageNumber=1&pageSize=20&searchTerm=Coro
api-version: 1.0
Authorization: Bearer {{accessToken}}

### Get work order by Id 
GET {{baseUrl}}/work-orders/{{workOrderId}}
api-version: 1.0
Authorization: Bearer {{accessToken}}

###! Create workorder (check data is valid before create)
POST {{baseUrl}}/work-orders
api-version: 1.0
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "vehicleId": "4a0c2e4b-5e0a-6a3c-b1bd-4c5e2f0d4004",
  "repairTaskId": "3c4d5e6f-7a8b-4c9d-ae1f-2a3b4c5d6e7f",
  "laborId": "{{laborAliceId}}",
  "startAt": "2026-06-15T16:00:00Z",
  "duration": "00:30:00"
}
